Evoting/Models/Candidate.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Degree { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Coin { get; set; }
        public string Public_Key { get; set; }
    }
}

Evoting/Controllers/CandidatesController.cs
using Evoting.Models;
using Evoting.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Evoting.Controllers
{
    public class CandidatesController : Controller
    {
        private readonly EvoteEntities1 db = new EvoteEntities1();
        // GET: Candidates
        #region Index
        /// <summary>
        ///     Candidates list view
        /// </summary>
        /// <returns>Candidates list</returns>
        public ActionResult Index()
        {
            var user = Session["UserSession"] as UserSession;
            if (user == null)
            {
                return RedirectToAction("Index", "Vote");
            }
            var candidates = db.Candidates.ToList();
            Random rnd = new Random();
            int r = rnd.Next(candidates.Count());

            ViewBag.RndCandidate = candidates[r];
            ViewBag.Candidates = candidates;
            return View();
        }

        #endregion

        #region CandidateDetail
        /// <summary>
        ///     Candidate detail view
        /// </summary>
        /// <returns>Candidate detail</returns>
        public ActionResult CandidateDetail(int _id = 0)
        {
            var user = Session["UserSession"] as UserSession;
            if (user == null)
            {
                return RedirectToAction("Index", "Vote");
            }
            if ( _id == 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var candidate = db.Candidates.SingleOrDefault(x => x.ID.Equals(_id));
                var candidates = db.Candidates.Where(x => x.ID != _id).Take(6).ToList();
                var _user = db.Users.SingleOrDefault(x => x.Username.Equals(user.Username));

                ViewBag.Candidates = candidates;
                ViewBag.Candidate = candidate;
                ViewBag.User = _user;
                return View();
            }           
        }

        #endregion

        #region CandidateVote

        /// <summary>
        ///     Encrypt vote with public key
        /// </summary>
        /// <param name="_id">Block id</param>
        /// <returns>Passing encrypt vote to AR to verify</returns>
        public ActionResult CandidateVote(int _id)
        {
            var user = Session["UserSession"] as UserSession;
            if (user == null)
            {
                return RedirectToAction("Index", "Vote");
            }
            var checkVote = db.Users.SingleOrDefault(x => x.Username.Equals(user.Username));
            if(checkVote.Voted != 1)
            {
                var _candidate = db.Candidates.SingleOrDefault(x => x.ID.Equals(_id));

                RSACryptoServiceProvider rsa = new RSACryptoServiceProvider();
                string _pubkey = rsa.ToXmlString(false);
                string _prikey = rsa.ToXmlString(true);

                Session["PrivateKeySession"] = new PrivateKeySession { PrivateKey = _prikey };
                var encryptedVote = Convert.ToBase64String(VoteModel.RSAEncrypt(Encoding.Unicode.GetBytes(_candidate.Name), _pubkey));

                return RedirectToAction("Index", "AR", new { _id = _id, _dataBase64 = encryptedVote });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        #endregion
    }
}

Evoting/Views/Candidates/CandidateDetail.cshtml
@{ 
    var candidate = ViewBag.Candidate as Evoting.Models.Candidate;
    var candidates = ViewBag.Candidates as List<Evoting.Models.Candidate>;
    var user = ViewBag.User as Evoting.Models.User;
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<!DOCTYPE html>
<html>

<!-- Mirrored from coffeecreamthemes.com/themes/jobseek/site/company.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 Jul 2015 04:55:20 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Jobseek - Job Board Responsive HTML Template">
    <meta name="author" content="Coffeecream Themes, info@coffeecream.eu">
    <title>@candidate.Name</title>
    <link rel="shortcut icon" href="/Content/images/favicon.png">

    <!-- Main Stylesheet -->
    <link href="/Content/CSS/style.css" rel="stylesheet">

    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body style="margin-top: -200px">

    <!-- ============ PAGE LOADER START ============ -->

    <div id="loader">
        <i class="fa fa-cog fa-4x fa-spin"></i>
    </div>

    <!-- ============ PAGE LOADER END ============ -->
    <!-- ============ TITLE START ============ -->

    <section id="title">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <img src="/Content/images/client-logo-big.gif" class="img-responsive" alt="" />
                </div>
            </div>
        </div>
    </section>

    <!-- ============ TITLE END ============ -->
    <!-- ============ CONTENT START ============ -->

    <section id="jobs">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    @*<article>*@
                    <h2>About @candidate.Name</h2>
                    <p>Maecenas mollis dictum lectus quis scelerisque. Nulla at rutrum ipsum. Praesent augue quam, facilisis vitae felis vel, convallis convallis nisi. Donec maximus accumsan purus vel tempus. Aenean pretium luctus velit id fermentum. Aenean non velit non nulla interdum venenatis. Integer in libero sagittis, consequat est quis, commodo odio. Aliquam eu vulputate neque. Nunc et massa leo. Vestibulum a pretium dolor. Proin et fermentum sapien. Cras malesuada neque ac purus fermentum, a placerat quam malesuada. Quisque sollicitudin tellus a ex eleifend mattis. In vitae ipsum in mauris vestibulum imperdiet.</p>
                    <p>Maecenas mollis dictum lectus quis scelerisque. Nulla at rutrum ipsum. Praesent augue quam, facilisis vitae felis vel, convallis convallis nisi. Donec maximus accumsan purus vel tempus. Aenean pretium luctus velit id fermentum. Aenean non velit non nulla interdum venenatis. Integer in libero sagittis, consequat est quis, commodo odio. Aliquam eu vulputate neque. Nunc et massa leo. Vestibulum a pretium dolor. Proin et fermentum sapien. Cras malesuada neque ac purus fermentum, a placerat quam malesuada. Quisque sollicitudin tellus a ex eleifend mattis. In vitae ipsum in mauris vestibulum imperdiet.</p>
                    <hr>
                    <h2>TDT Universiry</h2>


            
                    <hr>
                    <h2>Other Candidates</h2>
                    <section id="team">
                        <div class="container" style="margin-top:-180px">
                            <div class="col-sm-12 color1">
                                <div class="owl-carousel">
                                    @foreach (var item in candidates)
                                    {
                                        <!-- Team Member 1 -->
                                        <div><a href="@Url.Action("CandidateDetail",new { _id = item.ID})">
                                                 <div class="team-member text-center img-rounded color1" style="margin-top:10px">

                                                     <img src="~/Images/@item.Photo" class="img-responsive img-circle" alt="" style="max-width: 100px; max-height: 100px; width: 100px; height: 100px" />
                                                     <h5>@item.Name</h5>
                                                     <p>@item.Degree</p>
                                                     <p>
                                                         <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                                                         <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                                                         <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                                                         <a href="#"><i class="fa fa-instagram fa-2x"></i></a>
                                                     </p>
                                                 </div>
                                                </a>
                                            </div>
                                    }                                                     
                                </div>
                            </div>
                        </div>
                    </section>

                    @*</article>*@
                </div>
                <div class="col-sm-4" id="sidebar">
                    <div class="team-member text-center">
                        <img src="~/Images/@candidate.Photo" class="img-responsive " alt="" />
                        <h5>@candidate.Name</h5>
                        <h6>@candidate.Degree</h6>
                        <p>Aenean non velit non nulla interdum venenatis. Integer in libero sagittis, consequat est quis, commodo odio. Aliquam eu vulputate neque.</p>
                        <p>
                            <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                            <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                            <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                            <a href="#"><i class="fa fa-instagram fa-2x"></i></a>
                        </p>

                        <button type="button" class="btn btn-primary btn btn-danger" data-toggle="modal" data-target="#ComfirmModal">Vote for this candidate</button>
                        
                   
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="ComfirmModal" role="dialog">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">TDT Unidersity</h4>
                                </div>
                                <div class="modal-body">
                                    @if (user.Voted == 1)
                                    {
                                        <p>YOU HAD VOTED SUCCESSFULLY.</p>
                                        <p>YOU CAN NOT VOTE AGAIN</p>
                                    }
                                    else
                                    {
                                        <p>Do you want to vote for this candidate ?</p>
                                    }
                                </div>
                                <div class="modal-footer">
                                    @if (user.Voted == 1)
                                    {
                                        <button type="button" class="btn btn-danger " data-dismiss="modal">Cancel</button>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("CandidateVote", new { _id = candidate.ID})"><button type="button" class="btn btn-success" data-toggle="modal" data-target="#ComfirmModal">YES</button></a>
                                        <button type="button" class="btn btn-danger " data-dismiss="modal">NO</button>
                                    }
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--   end of Modal  -->

                    </div>
                </div>
            </div>



    </section>

    <!-- ============ CONTENT END ============ -->
   
</body>

<!-- Mirrored from coffeecreamthemes.com/themes/jobseek/site/company.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 Jul 2015 04:55:22 GMT -->
</html>

Evoting/Views/Candidates/Index.cshtml
@{
    var candidates = ViewBag.Candidates as List<Evoting.Models.Candidate>;
    var rndcandidates = ViewBag.RndCandidate as Evoting.Models.Candidate;
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<!DOCTYPE html>
<html>

<!-- Mirrored from coffeecreamthemes.com/themes/jobseek/site/candidates.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 Jul 2015 04:55:17 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Jobseek - Job Board Responsive HTML Template">
    <meta name="author" content="Coffeecream Themes, info@coffeecream.eu">
    <title>Candidates List</title>
    <link rel="shortcut icon" href="/Content/images/favicon.png">

    <!-- Main Stylesheet -->
    <link href="/Content/CSS/style.css" rel="stylesheet">

    <!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body style="margin-top: -200px">

    <!-- ============ PAGE LOADER START ============ -->

    <div id="loader">
        <i class="fa fa-cog fa-4x fa-spin"></i>
    </div>

    <!-- ============ PAGE LOADER END ============ -->
    <!-- ============ TITLE START ============ -->

    <section id="title">
        <div class="container jumbotron" style="margin-top: -100px">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h1>Candidates</h1>
                </div>
            </div>
        </div>
    </section>

    <!-- ============ TITLE END ============ -->
    <!-- ============ JOBS START ============ -->

    <section id="jobs">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <h2>Candidates</h2>

                    <div class="jobs">
                        @foreach (var item in candidates)
                        {
                            <!-- Job offer 1 -->
                            <a href="@Url.Action("CandidateDetail", "Candidates", new { _id = item.ID})">
                                <img src="/Images/@item.Photo" alt="" class="img-circle" style="max-width: 100px; max-height: 100px; width: 100px; height: 100px" />
                                <div class="title">
                                    <h5>@item.Name</h5>
                                    <p>@item.Degree</p>
                                </div>
                                <div class="data">
                                    <span class="city"><i class="fa fa-map-marker"></i>@item.Address</span>
                                    <span class="experience"><i class="fa fa-trophy"></i>TDT University</span>
                                </div>
                            </a>
                        }                     

                    </div>


                </div>
                <div class="col-sm-4" id="sidebar">

                    <!-- Featured Jobs Start -->
                    <div class="sidebar-widget">
                        <h2>Featured Candidate</h2>
                        <a href="@Url.Action("CandidateDetail", new { _id = @rndcandidates.ID})">
                            @*<img src="/Content/images/featured-job.jpg" alt="Featured Job" class="img-responsive" />*@
                            <div class="featured-job">
                                <img src="/Images/@rndcandidates.Photo" alt="" class="img-circle pull-left" style="max-width: 200px; max-height: 200px; width: 200px; height: 200px" />
                                <div class="title">
                                    <h5>@rndcandidates.Name</h5>
                                    <p>@rndcandidates.Degree</p>
                                </div>
                                <div class="data">
                                    <span class="city"><i class="fa fa-map-marker"></i>@rndcandidates.Address</span>
                                    <span class="experience"><i class="fa fa-trophy"></i>TDT University</span>
                                </div>
                                <div class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique euismod lorem, a consequat orci consequat a. Donec ullamcorper tincidunt nunc, ut aliquam est pellentesque porta. In neque erat, malesuada sit amet orci ac, laoreet laoreet mauris.</div>
                            </div>
                        </a>
                    </div>
                    <!-- Featured Jobs End -->

                </div>
            </div>
        </div>
    </section>

    <!-- ============ JOBS END ============ -->
   
</body>

<!-- Mirrored from coffeecreamthemes.com/themes/jobseek/site/candidates.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 Jul 2015 04:55:17 GMT -->
</html>